### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by newbiewow** [RealityNet/kobackupdec#11]
Hi, am having this error when i trying to use the script

`Traceback (most recent call last):
  File "D:\Program Files\Python\lib\pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'D:\\HiSuiteBackup\\data\\data\\com.amazon.avod.thirdpartyclient\\files\\global\\global_video_cache\\amzn1.dv.gti.30b18480-5c77-6536-71a1-f865650468ce\\es-419_dialog_0\\amzn1.dv.vcid.d9575003-f046-4188-b0c2-569a897b1ed8_37fcbd71-e663-3021-b6a8-372582035b9a$2b691e4dd78e947b25beb85e9bfc8de2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kobackupdec.py", line 926, in <module>
    main(user_password, backup_path, dest_path)
  File "kobackupdec.py", line 862, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File "kobackupdec.py", line 806, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File "kobackupdec.py", line 694, in decrypt_files_in_root
    tar_extract_win(tar_data, data_app_dir)
  File "kobackupdec.py", line 628, in tar_extract_win
    new_dir.mkdir(parents=True, exist_ok=True)
  File "D:\Program Files\Python\lib\pathlib.py", line 1273, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "D:\Program Files\Python\lib\pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'D:\\HiSuiteBackup\\data\\data\\com.amazon.avod.thirdpartyclient\\files\\global\\global_video_cache\\amzn1.dv.gti.30b18480-5c77-6536-71a1-f865650468ce\\es-419_dialog_0\\amzn1.dv.vcid.d9575003-f046-4188-b0c2-569a897b1ed8_37fcbd71-e663-3021-b6a8-372582035b9a$2b691e4dd78e947b25beb85e9bfc8de2'`

**Comment by lp4n6** [comment]
The script does not work on Linux if not run with sudo permissions. Maybe do you get a permission issue also on some Windows configurations. Would you like to try with my patch (https://github.com/lp4n6/kobackupdec/tree/patch-3). Please note it is not (yet?) validated by RealityNet.

**Comment by lp4n6** [comment]
It seems you encounter the exact same issue as https://github.com/RealityNet/kobackupdec/issues/12. Try with another Python 3 version.

**Comment by dfirfpi** [comment]
Thanks @lp4n6 for taking care of this.
The latest version has included your "permissions" patch, so it should not be an issue anymore.

Please @newbiewow, try it and let me know.

**Be careful**: on Windows there is a problem with such long paths...
