### ISSUE TITLE
malformed command error

### ISSUE THREAD

**Issue by nocomp** [RealityNet/kobackupdec#12]
hi folks,
thxx for this great tool, sold my huawei and forgot backup was encrypted...
i try to run the script, but no luck..
when i run this:
root@sandbox:/media/root/My Passport/backup-mate20# python3 kobackupdec.py -v my_password enc/HUAWEIMate20Pro_2020-01-14/ dec/

i get this:
root@sandbox:/media/root/My Passport/backup-mate20# python3 kobackupdec.py -v my_password enc/HUAWEIMate20Pro_2020-01-14/ dec-2020/
python3 kobackupdec.py -v my_passwordpython3.7 kobackupdec.py -vvv my_passwordpython3 kobackupdec.py -v my_passwordpython3 kobackupdec.py -v my_password enc/HUAWEIMate20Pro_2020-01-14/ dec/ enc/HUAWEIMate20Pro_2020-01-14/ dec/pyhton3  enc/HUAWEIMate20Pro_2020-01-14/ dec-huawei/ enc/HUAWEIMate20Pro_2020-01-14/ dec-2020/
usage: kobackupdec.py [-h] [-v] password backup_path dest_path
kobackupdec.py: error: unrecognized arguments: kobackupdec.py my_passwordpython3 kobackupdec.py my_password enc/HUAWEIMate20Pro_2020-01-14/ dec/ enc/HUAWEIMate20Pro_2020-01-14/ dec/pyhton3 enc/HUAWEIMate20Pro_2020-01-14/ dec-huawei/ enc/HUAWEIMate20Pro_2020-01-14/ dec-2020/

when i press the up arrow touch to see the command that i ve typed, it gives me this:

root@sandbox:/media/root/My Passport/backup-mate20# python3 kobackupdec.py -v my_passwordpython3.7 kobackupdec.py -vvv my_passwordpython3 kobackupdec.py -v my_passwordpython3 kobackupdec.py -v my_password enc/HUAWEIMate20Pro_2020-01-14/ dec/ enc/HUAWEIMate20Pro_2020-01-14/ dec/pyhton3  enc/HUAWEIMate20Pro_2020-01-14/ dec-huawei/ enc/HUAWEIMate20Pro_2020-01-14/ dec-2020/   !!!!!!!!!!!!!!!!!!!!!!

this is crazy! any idea why?

thxx for your time and your help

best regards

**Comment by lp4n6** [comment]
Try to run the script from a path without space(s). Yours includes a space between My and Passport. Or do you have a space in your password? If yes, try to quote it.

**Comment by nocomp** [comment]
hi @lp4n6 
thxx i ll try, just discovered that it corrupted the backupinfo.ini file; had to chkdsk /f the drive for delete it ..

**Comment by nocomp** [comment]
hmmmmmm on linux it s a disater...
nocomp@RFB0x:~/div/kobackupdec$ python3 kobackupdec.py -vvv password /home/nocomp/Images/mate20/mate20/ /home/nocomp/Images/mate20/decrypt/
python3 kobackupdec.py -vvv passwordpython3 kobackupdec.py -vvv passworddf -h /home/nocomp/Images/mate20/mate20/ /home/nocomp/Images/mate20/decrypt /home/nocomp/Images/mate20/mate20/ /home/nocomp/Images/mate20/decrypt/
usage: kobackupdec.py [-h] [-v] password backup_path dest_path

no idea why it show a weird command when i press up arrow to call the last one

this is weird

**Comment by nocomp** [comment]
hi @lp4n6 
finally been able to run it on windows, but got a crash  after a bit of work :/
INFO:root:working on com.facebook.katana&split_streamingsdk.apk
INFO:root:working on com.facebook.katana.apk
INFO:root:working on com.facebook.katana.tar
DEBUG:root:searching key [com.facebook.katana] of info_type.FILE
DEBUG:root:decrypt info  [com.facebook.katana] found
Traceback (most recent call last):
  File ".\kobackupdec.py", line 917, in <module>
    main(user_password, backup_path, dest_path)
  File ".\kobackupdec.py", line 862, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File ".\kobackupdec.py", line 806, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File ".\kobackupdec.py", line 689, in decrypt_files_in_root
    cleartext = decrypt_entry(decrypt_info, entry,
  File ".\kobackupdec.py", line 645, in decrypt_entry
    cleartext = decrypt_info.decryptor.decrypt_package(
  File ".\kobackupdec.py", line 299, in decrypt_package
    return decryptor.decrypt(data)
  File "C:\Users\herve\AppData\Roaming\Python\Python38\site-packages\Crypto\Cipher\_mode_ctr.py", line 276, in decrypt
    return get_raw_buffer(plaintext)
  File "C:\Users\herve\AppData\Roaming\Python\Python38\site-packages\Crypto\Util\_raw_api.py", line 187, in get_raw_buffer
    return buf.raw
MemoryError
PS D:\android\mate20pro\backupjanv2020\kobackupdec-master>

**Comment by lp4n6** [comment]
It looks like you could have an issue with your dependency|ies related to your Python 3.8...

**Comment by nocomp** [comment]
hmm this is weird, got this error on all windows pc on wich i try it
how can i solve this?
thxx for your time

**Comment by lp4n6** [comment]
Try pip3 install --upgrade cryptography and/or pip3 install --upgrade pycryptodome.

By the way, which version of HiSuite or backup app on your phone do you used?

**Comment by nocomp** [comment]
i ll try tomorrow i can t do thaht now, and i ll let you know
i ve used the version 10.0.0.510-ove

**Comment by nocomp** [comment]
hi @lp4n6 
thx for your advices, it did much more than last time but ended again with same kind of error

INFO:root:working on de.syss.MifareClassicTool.apk
INFO:root:working on de.syss.MifareClassicTool.tar
DEBUG:root:searching key [de.syss.MifareClassicTool] of info_type.FILE
DEBUG:root:decrypt info  [de.syss.MifareClassicTool] found
INFO:root:working on deezer.android.app.apk
INFO:root:working on deezer.android.app.tar
DEBUG:root:searching key [deezer.android.app] of info_type.FILE
DEBUG:root:decrypt info  [deezer.android.app] found
Traceback (most recent call last):
  File ".\kobackupdec.py", line 917, in <module>
    main(user_password, backup_path, dest_path)
  File ".\kobackupdec.py", line 862, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File ".\kobackupdec.py", line 806, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File ".\kobackupdec.py", line 689, in decrypt_files_in_root
    cleartext = decrypt_entry(decrypt_info, entry,
  File ".\kobackupdec.py", line 646, in decrypt_entry
    decrypt_material, entry.read_bytes())
  File "C:\Python\Python38-32\lib\pathlib.py", line 1223, in read_bytes
    return f.read()
MemoryError
PS H:\personel\backup-mate20pro\kobackupdec-master>

**Comment by nocomp** [comment]
retried,
same error same stage during the process
INFO:root:working on deezer.android.app.apk
INFO:root:working on deezer.android.app.tar
DEBUG:root:searching key [deezer.android.app] of info_type.FILE
DEBUG:root:decrypt info  [deezer.android.app] found
Traceback (most recent call last):
  File ".\kobackupdec.py", line 917, in <module>
    main(user_password, backup_path, dest_path)
  File ".\kobackupdec.py", line 862, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File ".\kobackupdec.py", line 806, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File ".\kobackupdec.py", line 689, in decrypt_files_in_root
    cleartext = decrypt_entry(decrypt_info, entry,
  File ".\kobackupdec.py", line 646, in decrypt_entry
    decrypt_material, entry.read_bytes())
  File "C:\Python\Python38-32\lib\pathlib.py", line 1223, in read_bytes
    return f.read()
MemoryError
PS H:\personel\backup-mate20pro\kobackupdec-master>

**Comment by lp4n6** [comment]
This is weird and I cannot identify the source of your issue :(. Maybe try this: https://projectfullstack.com/install-python-3-8-on-windows-10/

**Comment by nocomp** [comment]
this is the version i have :(
i am coarsed...
maybe i should try a 3.7

**Comment by nocomp** [comment]
bonjour @lp4n6 
i ve retried using python 3.5.2 and all worked like a charm
thank you so much, really appreciated.
i close the issue
have a nice day!
