### ISSUE TITLE
No backup1 folder nor info.xml file found!

### ISSUE THREAD

**Issue by jonmert** [RealityNet/kobackupdec#13]
Hi,

trying to decrypt a backup created with HiSuite 10.0.0.510_OVE I am getting following error:

No backup1 folder nor info.xml file found!

Indeed there is no backup1 nor info.xml in the backup directory. Files are encrypted with .enc extensions.

**Comment by jonmert** [comment]
I have a backupinfo.ini . Is it possible to build a info.xml out of this?

**Comment by Joshfindit** [comment]
Also have this issue (though I don’t have ini files either).
Thought it was an error in copying (friend sent me their backup to decrypt), but now suspecting it’s how the backup was made.

It’s from a P30

**Comment by lp4n6** [comment]
backup1 is a subfolder of your backup hierarchy. Search for it (for example with tree command). You may found more than one, take the one which is not empty.

**Comment by jonmert** [comment]
> backup1 is a subfolder of your backup hierarchy. Search for it (for example with tree command). You may found more than one, take the one which is not empty.

Sorry, but in the whole hierarchy there is no backup1.

`C:\USERS\JMERTENS\DOCUMENTS\HISUITE\BACKUP\HUAWEI MATE 10 LITE_2020-01-18 16.18.03
├───audio
│   └───storage
│       ├───Download
│       ├───Notifications
│       └───WhatsApp
│           └───Media
│               └───WhatsApp Audio
├───document
│   └───storage
│       ├───Android
│       │   ├───data
│       │   │   ├───com.dropbox.android
│       │   │   │   └───files
│       │   │   │       └───u241828913
│       │   │   │           └───scratch
│       │   │   ├───com.google.android.gm
│       │   │   │   └───cache
│       │   │   ├───com.microsoft.teams
│       │   │   │   └───files
│       │   │   │       └───Download
│       │   │   └───epson.print
│       │   │       └───cache
│       │   │           └───tempCR
│       │   └───media
│       ├───bluetooth
│       ├───Download
│       ├───Epson iPrint
│       └───WhatsApp
│           └───Media
│               └───WhatsApp Documents
│                   └───Sent
├───picture
│   └───storage
│       ├───DCIM
│       │   ├───Camera
│       │   └───Facebook
│       ├───Download
│       ├───EditedOnlinePhotos
│       ├───Epson iPrint
│       ├───Huawei
│       │   └───MagazineUnlock
│       ├───Pictures
│       │   └───Screenshots
│       └───WhatsApp
│           └───Media
│               ├───WhatsApp Documents
│               └───WhatsApp Images
└───video
    └───storage
        ├───DCIM
        │   └───Camera
        └───WhatsApp
            └───Media
                ├───WhatsApp Animated Gifs
                └───WhatsApp Video`

**Comment by lp4n6** [comment]
I am pretty sure your output it is not the "raw" output from HiSuite, but only a subset/subfolder from the whole backup. Could you try again from scratch?

**Comment by jonmert** [comment]
C:\Users\jmertens\Documents\HiSuite>tree
Auflistung der Ordnerpfade
Volumeseriennummer : 00690048 FEA7:81FC
C:.
├───backup
│   ├───HUAWEI Mate 10 lite_2020-01-18 16.18.03
│   │   ├───audio
│   │   │   └───storage
│   │   │       ├───Download
│   │   │       ├───Notifications
│   │   │       └───WhatsApp
│   │   │           └───Media
│   │   │               └───WhatsApp Audio
│   │   ├───document
│   │   │   └───storage
│   │   │       ├───Android
│   │   │       │   ├───data
│   │   │       │   │   ├───com.dropbox.android
│   │   │       │   │   │   └───files
│   │   │       │   │   │       └───u241828913
│   │   │       │   │   │           └───scratch
│   │   │       │   │   │               └───KLJB Schwaney
│   │   │       │   │   │                   └───Freizeit
│   │   │       │   │   ├───com.google.android.gm
│   │   │       │   │   │   └───cache
│   │   │       │   │   ├───com.microsoft.teams
│   │   │       │   │   │   └───files
│   │   │       │   │   │       └───Download
│   │   │       │   │   └───epson.print
│   │   │       │   │       └───cache
│   │   │       │   │           └───tempCR
│   │   │       │   └───media
│   │   │       ├───bluetooth
│   │   │       ├───Download
│   │   │       ├───Epson iPrint
│   │   │       └───WhatsApp
│   │   │           └───Media
│   │   │               └───WhatsApp Documents
│   │   │                   └───Sent
│   │   ├───picture
│   │   │   └───storage
│   │   │       ├───DCIM
│   │   │       │   ├───Camera
│   │   │       │   └───Facebook
│   │   │       ├───Download
│   │   │       ├───EditedOnlinePhotos
│   │   │       ├───Epson iPrint
│   │   │       ├───Huawei
│   │   │       │   └───MagazineUnlock
│   │   │       ├───Pictures
│   │   │       │   └───Screenshots
│   │   │       └───WhatsApp
│   │   │           └───Media
│   │   │               ├───WhatsApp Documents
│   │   │               └───WhatsApp Images
│   │   └───video
│   │       └───storage
│   │           ├───DCIM
│   │           │   └───Camera
│   │           └───WhatsApp
│   │               └───Media
│   │                   ├───WhatsApp Animated Gifs
│   │                   └───WhatsApp Video
│   ├───Pictures
│   │   ├───.Gallery2
│   │   │   └───recycle
│   │   ├───Messenger
│   │   └───Screenshots
└───Screenshot

**Comment by lp4n6** [comment]
This is my hierarchy from a backup I just did (from the backup app, directly from the phone on an USB storage key plugged through an OTG cable). Obviously, yours is... strange.

You should have a Huawei root folder, then Backup. This is not a script related issue.

I:.
+---Android
|   \---data
|       +---com.huawei.android.thememanager
|       |   \---cache
|       +---com.touchtype.swiftkey
|       |   \---files
|       +---com.huawei.systemmanager
|       |   +---files
|       |   \---cache
|       \---com.huawei.search
|           +---files
|           \---cache
\---Huawei
    \---Backup
        +---AMD FTP uxt __a6300a1ffd9b78583bdb07158e590fca26cd6f80e36b39073506c66234fc0f32__
        |   +---backupFiles
        |   +---backupFiles1
        |   +---media
        |   |   +---photo
        |   |   +---video
        |   |   \---recording
        |   \---AutoBackup
        |       +---backupFiles
        |       \---backupFiles1
        \---AMD FTP uxt __a6300a1ffd9b78583bdb07158e590fca26cd6f80e36b39073506c66234fc0f32__de2bd9554d43129bad9968ce39d5a321
            +---backupFiles1
            |   \---2020-01-29_13-15-25-362
            |       +---soundrecorder
            |       |   \---Sounds
            |       +---com.tcx.sipphone14
            |       +---com.alibaba.aliexpresshd
            |       +---ch.rts.rtsinfo
            |       +---com.supercell.brawlstars
            |       +---com.google.android.apps.tachyon
            |       +---com.facebook.katana
            |       +---com.ovelin.guitartuna
            |       +---com.linkedin.android
            |       +---ch.hrtop.android
            |       +---com.google.android.apps.maps
            |       +---net.androgames.level
            |       +---com.google.android.apps.photos
            |       +---com.shazam.android
            |       +---com.snapchat.android
            |       +---com.zhiliaoapp.musically
            |       +---com.twitter.android
            |       \---com.google.android.youtube
            \---media
                \---2020-01-29_13-15-25-362
                    +---pictures
                    |   +---WhatsApp
                    |   |   \---Media
                    |   |       \---WhatsApp Images
                    |   +---Pictures
                    |   |   +---Screenshots
                    |   |   +---9GAG
                    |   |   +---LinkedIn
                    |   |   +---codm
                    |   |   \---Messages
                    |   +---Download
                    |   \---DCIM
                    |       \---Facebook
                    +---photo
                    |   \---DCIM
                    |       \---Camera
                    +---movies
                    |   +---WhatsApp
                    |   |   \---Media
                    |   |       +---WhatsApp Video
                    |   |       \---WhatsApp Animated Gifs
                    |   \---Pictures
                    |       +---9GAG
                    |       \---Screenshots
                    +---video
                    |   \---DCIM
                    |       \---Camera
                    \---doc
                        +---WhatsApp
                        |   \---Media
                        |       \---WhatsApp Documents
                        |           \---Sent
                        +---Download
                        +---tencent
                        |   \---Midas
                        |       \---Log
                        |           \---com.activision.callofduty.shooter
                        +---Android
                        |   \---data
                        |       +---com.google.android.apps.maps
                        |       |   \---testdata
                        |       |       \---voice
                        |       |           \---fr_CHf8a6aec0
                        |       +---com.activision.callofduty.shooter
                        |       |   \---files
                        |       |       \---tbslog
                        |       \---com.zhiliaoapp.musically
                        |           \---cache
                        \---Sounds
                            \---.backup

**Comment by Joshfindit** [comment]
> This is my hierarchy from a backup I just did (from the backup app, directly from the phone on an USB storage key plugged through an OTG cable). Obviously, yours is... strange.
> 
> You should have a Huawei root folder, then Backup. This is not a script related issue.

The backup program for some seems to be making a folder structure that the script doesn't understand. Is it possible we're seeing a new version?

As evidence: you also don't have a "HUAWEI P30 Pro_2020-01-21 22.34.47"/"HUAWEI Mate 10 lite_2020-01-18 16.18.03"/YOURMODELHERE folder

**Comment by dfirfpi** [comment]
@Joshfindit 
is it possible they changed something. Actually I've not yet encountered the folders structure you posted. You still should be able to point the script to the folder containing the info.xml file. Do you have such a file? I would expect to have two identical info.xml files... let me know, thanks

**Comment by RussiaVk** [comment]
same problem

**Comment by dfirfpi** [comment]
Without any sample, even partial, I cannot work on it.

**Comment by Kekht** [comment]
I have the same problem - backed up at 2020-02-17 only videos and photos,
Inside my Honor 9_2020-02-17 00.48.29 directoryr there are only two directories - 'picture' and 'video'. backupinfo.ini (which, as I saw, contains pwdsalt_iv and pwdsalt (as hex) and hashed password) and some other files. There are no info.xml
BTW that day (2020-02-17) I have made separate backup of other data like contacts and messages - info.xml present.

Here is my tree:
```
/Backups/HiSuite/Honor 9_2020-02-17 00.48.29/
├── backupinfo.ini
├── image_MediaInfo.db.enc
├── picture
│   └── storage
│       ├── DCIM
│       │   ├── Camera
│       │   │   ├── IMG_20190509_105421.jpg.enc
│       │   │   ...
│       │   │   └── IMG_20200216_150346.jpg.enc
│       │   └── Facebook
│       │       ├── FB_IMG_1561535973291.jpg.enc
│       │       ├── FB_IMG_1563111902873.jpg.enc
│       │       └── FB_IMG_1563794402713.jpg.enc
│       ├── Download
│       │   ├── 1361617540_1349056823.jpg.enc
│       │    ...
│       │   └── profili.jpg.enc
│       ├── Huawei
│       │   └── MagazineUnlock
│       │       ├── MagazinePic-01-2.3.001-bigpicture_01_1.jpg.enc
│       │       └── magazine-unlock-05-2.3.1054-_E324CBF20DC4268A2AC0A0DCDAD7FFBD.jpg.enc
│       ├── Pictures
│       │   ├── 1544372229916.jpg.enc
│       │   ├── Facebook
│       │   │   └── IMG_1561795061424.jpg.enc
│       │   ├── Telegram
│       │   │   └── IMG_20181119_144751_498.jpg.enc
│       │   └── ae_1547838189550.jpg.enc
│       └── WhatsApp
│           └── Media
│               └── WhatsApp Images
│                   └── IMG-20171229-WA0000.jpg.enc
├── picture.xml
├── video
│   └── storage
│       ├── DCIM
│       │   └── Camera
│       │       ├── VID_20180811_125314.mp4.enc
│       │       └── VID_20200208_165246.mp4.enc
│       ├── Pictures
│       │   └── Telegram
│       │       └── VID_20190405_101125_544.mp4.enc
│       └── WhatsApp
│           └── Media
│               └── WhatsApp Video
│                   ├── VID-20180903-WA0015.mp4.enc
│                   └── VID-20200215-WA0000.mp4.enc
├── video.xml
└── video_MediaInfo.db.enc
```
Here is sample of picture.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Multimedia>
    <File>
        <Path>\storage\DCIM\Camera\IMG_20200216_150346.jpg</Path>
        <Iv>3614E5E5F9AC5C5E8231BC9A8918BCC9</Iv>
    </File>
</Multimedia>
```

and here is sample of video.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Multimedia>
    <File>
        <Path>\storage\DCIM\Camera\VID_20200208_123314.mp4</Path>
        <Iv>3B0AE361AD5C017EDB64222D4DC9A6CD</Iv>
    </File>
</Multimedia>
```
Can you add feature, that if there is no info.xml but present video.xml and picture.xml (and related directories) - try to encode them?

**Comment by padma2012** [comment]
Has anyone managed to solve this issue for the Huawei backup when no info.xml file is found?
