### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by Riflerat** [RealityNet/kobackupdec#15]
Hello, I have a problem here:

$ ./kobackupdec.py -vvv passwd "/home/l/dec/HUAWEI P smart 2019_2020-01-15 06.08.10" "/home/l/dec/kobackupdec/oo"
INFO:root:searching backup in [/home/l/dec/HUAWEI P smart 2019_2020-01-15 06.08.10]
INFO:root:got info.xml, going to decrypt backup files
INFO:root:Parsing file /home/l/dec/HUAWEI P smart 2019_2020-01-15 06.08.10/info.xml
DEBUG:root:Ignoring HeaderInfo entry.
DEBUG:root:Ignoring BackupFilePhoneInfo entry
DEBUG:root:Ignoring BackupFileVersionInfo entry
DEBUG:root:Parsing BackupFilesTypeInfo
DEBUG:root:crypto_init: using version 3.
DEBUG:root:SHA256(BKEY)[16] = b'ed75c3ed63f5a2604a855c28d3d3a91b'
DEBUG:root:SALT[32] = b'67a093e3709f07b41cf0a112fd0427e04ec2b4a9e684c14b8ecdbeca9f11481e'
Traceback (most recent call last):
  File "./kobackupdec.py", line 917, in <module>
    main(user_password, backup_path, dest_path)
  File "./kobackupdec.py", line 862, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File "./kobackupdec.py", line 790, in decrypt_backup
    decrypt_info = parse_info_xml(path_in.joinpath('info.xml'), password)
  File "./kobackupdec.py", line 576, in parse_info_xml
    dec_info.decryptor = decryptor
  File "./kobackupdec.py", line 395, in decryptor
    new_decryptor.crypto_init()
  File "./kobackupdec.py", line 269, in crypto_init
    Decryptor.prf, hmac_hash_module=None)
TypeError: PBKDF2() got an unexpected keyword argument 'hmac_hash_module'

Can you help me to fix it?

**Comment by lp4n6** [comment]
Hi Riflerat,
My skills are not good enough to solve your problem. We probably have to wait on RealityNet. Anyway, maybe you could provide the backup app version and the info.xml file for debugging purpose.

**Comment by Riflerat** [comment]
I don't know Python language. Probably it can be trivial bug (if it a bug). That should be best if developer will answer or help me to install any missing modules or something...

**Comment by lp4n6** [comment]
I don't know exactly which part is relevant :(. You can attach a file by drag & drop.

By the way, do you use Python 3.7+ and do you have installed dependency (PyCryptodome)?

**Comment by bixiu** [comment]
delete every “hmac_hash_module” and  it can run ok，you can try this

**Comment by dfirfpi** [comment]
@Riflerat 
Please install pycryptodome

pip3 install --user pycryptodome.
