### ISSUE TITLE
Why setting all decrypted files to read-only?

### ISSUE THREAD

**Issue by schmaun** [RealityNet/kobackupdec#16]
Hey there,

first, thank you very much for this tool. Speeded up the recovery a lot because I didn't had to wait for those timeouts (e.g 59 minutes) after entering the wrong password.

After decrypting the files I got the following error:
```
Traceback (most recent call last):
  File "kobackupdec.py", line 917, in <module>
    main(user_password, backup_path, dest_path)
  File "kobackupdec.py", line 876, in main
    os.chmod(entry, 0o444)
PermissionError: [Errno 13] Permission denied: '<removed>/data/data'
```
The folder got "dr--r--r--".

I was wondering why this was added at all?
https://github.com/RealityNet/kobackupdec/blob/0277282052fdc6fa0b51ad6f901d6fe672f77b6c/kobackupdec.py#L874

Have a nice weekend :)

**Comment by lp4n6** [comment]
Could be because this script was developed for forensics purpose. In this context, files have to be write protected because of integrity.

You can customize this feature by editing the script: os.chmod(entry, 0o444) -> os.chmod(entry, 0o777).

Regards.
