### ISSUE TITLE
If I tried to rename .jpg.enc to .jpg

### ISSUE THREAD

**Issue by psp-anon** [RealityNet/kobackupdec#19]
What to do if I tried to rename .jpg.enc to .jpg. I renamed it back to .jpg.enc but now password is wrong.

Anyone help!

**Comment by dfirfpi** [comment]
Hi @psp-anon ,
honestly speaking I cannot get your issue. What are you trying to do? If the images have extension .ENC, it should (speaking of kobackup) mean they are encrypted. By changing the extension you should not be able to see them. That's the reason of the script, to decrypt an encrypted kobackup, assumed you know the correct password.

**Comment by dfirfpi** [comment]
Closing the issue. If you want to open a different one with more details of what is not working, do that.
