### ISSUE TITLE
I can not decrypt my files!!!

### ISSUE THREAD

**Issue by aga-xyz** [RealityNet/kobackupdec#2]
Hello
I installed python27 on my computer then I did the other requirements. 
I opened CMD and entered the following command line:

`py -3 kobackupdec.py -vvv didarmasaud1 "C:\Python27\kobackupdec-master\bluetooth" C:\Python27\kobackupdec-master\out`

but it did not run and showed me the below message!! could you help to find it out?

> Traceback (most recent call last):
 > File "kobackupdec.py", line 44, in <module>
   > from Crypto.Cipher import AES
> ModuleNotFoundError: No module named 'Crypto'

**Comment by silvestro23** [comment]
Did you install pycryptodome ?

Read this article, follow **carefully** all the steps and you will able to decrypt your files

https://www.linkedin.com/pulse/huawei-backup-decrypt-gherardo-magnini/

**Comment by aga-xyz** [comment]
Thanks for replying me...
I did all the steps correctly, Now I faced this problem:

`- UNK file not handled:
-  has no decrypt material!` 

please tell me what should I do?
Thanks in advance

**Comment by silvestro23** [comment]
Can you post some screenshots?

**Comment by aga-xyz** [comment]
here is the issue

![73203609_2783220568396499_6114130411099521024_n](https://user-images.githubusercontent.com/22833344/67637804-3ca79a80-f8ef-11e9-83fb-d6c6c5e1b4ae.jpg)

**Comment by dfirfpi** [comment]
hi @aga-xyz,
could you please share how did you create the backup?
With the mobile application directly on sdcard / otg? With the HiSuite Windows software?
Which mobile app version are you using?

**Comment by dfirfpi** [comment]
Please try the latest version. If the issue persists, reopen the ticket, thanks.
