### ISSUE TITLE
Error Decrypting HiSuit Backup: cannot decrypt with an empty encMsgV3

### ISSUE THREAD

**Issue by malyahy2** [RealityNet/kobackupdec#21]
Hi I have been trying to decrypting my phone's back. However, I keep getting this issue with one of the backups.

General Info:
HiSuite Version: 10.0.1.100_OVE
Phone: Huawei Mate 20 Pro
Windows 10 
Python 3.7.5

Below is the output message:

ERROR:root:cannot decrypt with an empty encMsgV3!
Traceback (most recent call last):
  File "kobackupdec.py", line 932, in <module>
    main(user_password, backup_path, dest_path)
  File "kobackupdec.py", line 866, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File "kobackupdec.py", line 810, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File "kobackupdec.py", line 696, in decrypt_files_in_root
    with tarfile.open(fileobj=io.BytesIO(cleartext)) as tar_data:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by dfirfpi** [comment]
Hi @malyahy2 ,
that's unexpected because if unable to decrypt, None should be returned and tar error should be avoided... Did you change something in the script? Could you please try with the latest version?

**Comment by dfirfpi** [comment]
Try again with the latest version. Reopen the issue in case. Thanks.
