### ISSUE TITLE
Error Decrypting HiSuite Backup

### ISSUE THREAD

**Issue by 58vlukVyWit6PGn8bVC8** [RealityNet/kobackupdec#23]
General info:
PC1: HiSuite version 10.0.0.510_OVE
PC2: HiSuite version 10.0.1.100_OVE

Device: VOG-L29 (Huawei P30 Pro)
Huawei Backup version 10.1.1.500

Tried on different computers running Python 3.7.

I will also try a backup made to a USB flashdrive.

logging:

> INFO:root:searching backup in [HUAWEI P30 Pro_2020-05-11 09.09.41]
> INFO:root:got info.xml, going to decrypt backup files
> INFO:root:Parsing file <path>\HUAWEI P30 Pro_2020-05-11 09.09.41\info.xml
> DEBUG:root:Ignoring HeaderInfo entry.
> DEBUG:root:Ignoring BackupFilePhoneInfo entry
> DEBUG:root:Ignoring BackupFileVersionInfo entry
> DEBUG:root:Parsing BackupFilesTypeInfo
> DEBUG:root:crypto_init: using version 3.
> DEBUG:root:SHA256(BKEY)[16] = b'<key>'
> Traceback (most recent call last):
>   File "C:\hbu\kobackupdec.py", line 932, in <module>
>     main(user_password, backup_path, dest_path)
>   File "C:\hbu\kobackupdec.py", line 866, in main
>     decrypt_backup(password, files_folder, dest_path_out)
>   File "C:\hbu\kobackupdec.py", line 794, in decrypt_backup
>     decrypt_info = parse_info_xml(path_in.joinpath('info.xml'), password)
>   File "C:\hbu\kobackupdec.py", line 580, in parse_info_xml
>     dec_info.decryptor = decryptor
>   File "C:\hbu\kobackupdec.py", line 399, in decryptor
>     new_decryptor.crypto_init()
>   File "C:\hbu\kobackupdec.py", line 269, in crypto_init
>     salt = self._checkMsg[32:]
> TypeError: 'NoneType' object is not subscriptable

Update:
Also tried through a flash drive, to no avail:

> INFO:root:searching backup in [VOG-L29]
> INFO:root:got info.xml, going to decrypt backup files
> INFO:root:Parsing file [path]\VOG-L29\info.xml
> DEBUG:root:Ignoring HeaderInfo entry.
> DEBUG:root:Ignoring BackupFilePhoneInfo entry
> DEBUG:root:Ignoring BackupFileVersionInfo entry
> DEBUG:root:Parsing BackupFilesTypeInfo
> DEBUG:root:crypto_init: using version 4.
> DEBUG:root:KEY_SALT[16] = b'[key]'
> DEBUG:root:KEY[32] = b'[key]'
> DEBUG:root:KEY NONCE[16] = b'[key]'
> DEBUG:root:BKEY[32] =   b'[key]'
> DEBUG:root:SHA256(BKEY)[16] = b'[key]'
> Traceback (most recent call last):
>   File "C:\kobackupdec.py", line 932, in <module>
>     main(user_password, backup_path, dest_path)
>   File "C:\kobackupdec.py", line 866, in main
>     decrypt_backup(password, files_folder, dest_path_out)
>   File "C:\kobackupdec.py", line 794, in decrypt_backup
>     decrypt_info = parse_info_xml(path_in.joinpath('info.xml'), password)
>   File "C:\kobackupdec.py", line 580, in parse_info_xml
>     dec_info.decryptor = decryptor
>   File "C:\kobackupdec.py", line 399, in decryptor
>     new_decryptor.crypto_init()
>   File "C:\kobackupdec.py", line 269, in crypto_init
>     salt = self._checkMsg[32:]
> TypeError: 'NoneType' object is not subscriptable

**Comment by sherry1118** [comment]
we have the same problem, and we find this problem is coming from "checkMsg" in info.xml, which is empty in backup folder.

**Comment by PaulV1990** [comment]
I've noticed this also from Huawei Backup version 10.1.1.500.
Downgrading to Huawei Backup 10.1.0.350 is the last working version i know.

**Comment by realSnoopy** [comment]
cannot test it right know, but info.xml in backupfiles1\*date*\ and info.xml in \media\*date*\ are the same in my older backups, just try to replace the empty one with the one from media or vice versa

or is there no/empty info.xml in both folders?

**Comment by realSnoopy** [comment]
plz see my updated script where i fixed this issue
+ decrypt audio files
+ fast workaround for new style of backup without checkMsg -> no check whether provided passphrase is correct or not

**Comment by dfirfpi** [comment]
Thanks all for the info. It seems they are constantly changing stuffs... please follow @realSnoopy advice and try the last version of the script. Reopen the issue in case.
