### ISSUE TITLE
till the author comes online again [updated script]

### ISSUE THREAD

**Issue by realSnoopy** [RealityNet/kobackupdec#25]
plz see my updated script

for adressing other issues than these i already fixed
+ decrypt audio files
+ fast workaround for new style of backup without checkMsg -> no check whether provided passphrase is correct or not 

this could be possible by providing some sample data  (info.xml and encrypted not important files like background.jpg or someheavymetal.mp3)

**Comment by dfirfpi** [comment]
Thanks @realSnoopy! I'm pushing the script in few minutes.
