### ISSUE TITLE
kobackupdec.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by Kory20** [RealityNet/kobackupdec#28]
//Describe the bug

Starting the process the result was:

kobackupdec.py: error: unrecognized arguments: C:\Users\Kory2.0\Documents\HiSuite\backup\HUAWEI P8 lite_2018-09-29 04.21.10 C:\Users\Kory2.0\Documents\HiSuite

**Required info**
 - Huawei Kobackup version: Don't know the version but is posted 13/06/2020
 - Host: [Windows / Linux ]: windows 10
 - Kobackup script version: Don't know 
 - Kobackup output log (use -vvv): 

usage: kobackupdec.py [-h] [-e] [-w] [-v] password backup_path dest_path
kobackupdec.py: error: unrecognized arguments: C:\Users\Kory2.0\Documents\HiSuite\backup\HUAWEI P8 lite_2018-09-29 04.21.10 C:\Users\Kory2.0\Documents\HiSuite

[![Screenshot (155)](https://user-images.githubusercontent.com/41315126/84559064-0dd41c80-ad38-11ea-9508-cb70753b4b98.png)
](url)

**Comment by 17KryptoVos** [comment]
Could you try and remove (or escape) the spaces in the part: `HUAWEI P8 lite` in the arguments: `C:\Users\Kory2.0\Documents\HiSuite\backup\HUAWEI P8 lite_2018-09-29 04.21.10`

**Comment by dfirfpi** [comment]
Yep, as  @17KryptoVos suggested spaces are nobody best friend.
As the help highlights, the script requires at least "password" "backup path" "output path"
