### ISSUE TITLE
Feature Request - Skip Existing Files

### ISSUE THREAD

**Issue by Mohsyn** [RealityNet/kobackupdec#32]
Since backups can be really huge running into gigabytes,
can the script skip the files which already exist in target?

It takes me around 15 minutes before the script breaks 
because of some error and I have to start all over again.

Thanks :)

**Comment by dfirfpi** [comment]
I can get your point, but due to limited amount of time and the fact the tool is not an end-user one, I won't fix.

**Comment by Mohsyn** [comment]
Thank you so much for your efforts anyways.
Cheers
