### ISSUE TITLE
Module Crypto can't be found after installing

### ISSUE THREAD

**Issue by OkanAydinguel** [RealityNet/kobackupdec#34]
If you have installed all required modules and still get that error, probably you are using Python 3.xx or there is another issue.

Open the file kobackupdec.py and edit the imports: Write Cryptodome instead of Crypto and it should work like a charm.

Unfortunately, I installed many different crypto modules so I do not know which one is right for sure but it should be pip install pycryptodome or pip install pycryptodomex

**Comment by oO0oO0oO0o0o00** [comment]
The name of required module is written inside `requirements.txt`

**Comment by Kekht** [comment]
I had the same problem. So for Ubuntu (20 LTS) I have installed python3-pycryptodome
Also I had to change this
```from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto.Hash import HMAC
from Crypto.Protocol.KDF import PBKDF2
from Crypto.Util import Counter
```

to this
```from Cryptodome.Cipher import AES
from Cryptodome.Hash import SHA256
from Cryptodome.Hash import HMAC
from Cryptodome.Protocol.KDF import PBKDF2
from Cryptodome.Util import Counter
```

All that solved the problem.

**Comment by dfirfpi** [comment]
Thanks for solving by yourselves :)
In case of multiple libs, I'd suggest to use virtual-envs.
Accordingly to the latest pycryptodome.readthedocs.io, _import Crypto_ is correct.
