### ISSUE TITLE
Problem with Huawei phone encripted backup

### ISSUE THREAD

**Issue by AcaRadovanovic** [RealityNet/kobackupdec#35]
Hello people, I need help considering this topic, I have Huawei backup done directly from the phone Mate 10 Pro under Android 10, it was done from recovery mode with the Emergency Backup peocedure. BUT, backup didn't finished completely and correctly, some folders like pictures are completely copied, but I am missing some informational file called info.xml (and maybe also some others), and restore procedure from phone, or this Python script and procedure is not working because it can't locate this file and backup is not recognized, restore is not starting. My files that are successfully copied are normal size and with normal extensions, but they are crypted with password that I had to use, the password is not the problem, I know it, but I don't know how to decrypt now my files without complete informational files that are missing from backup structure. Any help, ideas, please?

**Comment by oO0oO0oO0o0o00** [comment]
Then do you have `cinfoset.dat` or `backupinfo.ini`? `cinfoset.dat` seems to be having identical content with `info.xml` so you can copy/rename it i guess. Don't know if `backupinfo.ini` is useful on its own as well. It also seems that the encryption uses not only user-entered password but also random salt (it's salt, not sh*t), so one or more of the info files are necessary. Not sure. **Better wait for the author to reply**.

**Comment by dfirfpi** [comment]
Hi @AcaRadovanovic 
Never got an Emergency Backup to with, so I don't know if there is something special (I guess..). Particularly a "broken" one. I would try to act as @oO0oO0oO0o0o00 suggested.
