### ISSUE TITLE
NOT WORK ANY MORE ON NEW VERSION HISUITE

### ISSUE THREAD

**Issue by RussiaVk** [RealityNet/kobackupdec#37]
**Describe the bug**

**NOTE**
Please consider that some errors could be handled only by providing the info.xml file and the files related to the issue (e.g. a file that cannot be decrypted). If the files needed to understand the bug could contain personal data of any kind, DO NOT SEND THEM. Instead, provide samples that can be shared and with a limited size. Thanks.

**Required info (please complete the following information):**
 - Huawei Kobackup version: 
 - Host: [Windows / Linux ]
 - Kobackup script version:
 - Kobackup output log (use -vvv)

**Additional context**

**Screenshots**

**Comment by oO0oO0oO0o0o00** [comment]
Revert to a previous versions of HiSuite. They can be easily found by searching its Chinese name with a reasonable version name such as "10.0.1.100" on Baidu, check results [here](https://www.baidu.com/s?wd=%E5%8D%8E%E4%B8%BA%E6%89%8B%E6%9C%BA%E5%8A%A9%E6%89%8B10.0.1.100) Use a translation service and find the real download buttons from each result. **Don't** get confused by the many fake "download" buttons that would actually get you a downloader filled with malwares.

**Comment by dfirfpi** [comment]
@RussiaVk 
Thanks for reporting but... no details, just a "it does not work with...". Which version is not working? Do you a previous version backup to check with? What changed? Any info?

Thanks @oO0oO0oO0o0o00 for the workaround.
