### ISSUE TITLE
Path not founded

### ISSUE THREAD

**Issue by diefer-rs** [RealityNet/kobackupdec#4]
I found out that the restoration of my backup file was wrong because I could not find some files. Those files are inside the backup folder but with the .enc extention.
I would like to decrypt only those files, mostly call records.
I run the script but I got the next error:
"the system is unable to find the specified path"
![image](https://user-images.githubusercontent.com/57760908/68864609-799eca00-0702-11ea-9734-6aa2b8b3480d.png)

**Comment by diefer-rs** [comment]
I removed com.evernote from the backup folder and worked fine.
Maybe you can add a skip this kind of error and not quit the script.

**Comment by dfirfpi** [comment]
Hi @diefer-rs ,
could you try using WSL? I mean using Linux, the error it's weird, could be related to some specific chars not allowed in Windows.

**Comment by dfirfpi** [comment]
Please try the latest head version. Re-open the ticket in case.
