### ISSUE TITLE
Bug file unmanged

### ISSUE THREAD

**Issue by ThePredato** [RealityNet/kobackupdec#42]
Huawei Kobackup version: 20200705
Host: [Windows / Linux ] Windows
Kobackup script version: 20200705
Kobackup output log (use -vvv) used -vvv

I have this message when I try to decode some files of one folder. The other files of that folder have been all decrypted, except some files, which are copied in a folder called "Uknown". Here is the output console message:

INFO:root:working on IMG_20190718_155409.jpg.enc
WARNING:root:entry IMG_20190718_155409.jpg.enc unmanged, copying it

How can I solve this?

**Comment by dfirfpi** [comment]
_Unmanaged_ means that the script was unable to find the decryption material related to that/those file(s). You could search in the XML files if there is any reference to that file (aka, bug in the script): if not, there is something I missed when reversing the app.
