### ISSUE TITLE
Password cannot be processed

### ISSUE THREAD

**Issue by estazz** [RealityNet/kobackupdec#8]
Hi, 

I tried to use your tool today to decrypt my backup I made on the weekend but did not succeed. 
Used the newest HiSuite version and Python 3.6.9 on WSL. I am getting the following error message while using my correct password:

`cr@Christian-PC:~/kobackupdec$ python3 kobackupdec.py -vvv 12345 "/mnt/c/Users/Christian/Desktop/Honor" "/mnt/c/Users/Christian/Desktop/Restored"
INFO:root:getting files and folder from /mnt/c/Users/Christian/Desktop/Honor
INFO:root:parsing XML files...
INFO:root:parsing xml audio.xml
DEBUG:root:parsing xml file audio.xml
INFO:root:parsing xml document.xml
DEBUG:root:parsing xml file document.xml
INFO:root:parsing xml info.xml
DEBUG:root:ignoring entry HeaderInfo
DEBUG:root:ignoring entry BackupFilePhoneInfo
DEBUG:root:ignoring entry BackupFileVersionInfo
INFO:root:parsing xml picture.xml
DEBUG:root:parsing xml file picture.xml
INFO:root:parsing xml video.xml
DEBUG:root:parsing xml file video.xml
DEBUG:root:crypto_init: using version 3.
DEBUG:root:SHA256(BKEY)[16] = b'5994471abb01112afcc18159f6cc74b4'
DEBUG:root:SALT[32] = b'a6d30fe041e62517e7beb081285919e85a902f2b02e9f6e490aaaa2ab557b136'
Traceback (most recent call last):
  File "kobackupdec.py", line 621, in <module>
    main(user_password, backup_path, dest_path)
  File "kobackupdec.py", line 450, in main
    decryptor.crypto_init()
  File "kobackupdec.py", line 228, in crypto_init
    Decryptor.prf, hmac_hash_module=None)
TypeError: PBKDF2() got an unexpected keyword argument 'hmac_hash_module'`

Any ideas? 
Sorry for raw ticket I am not a dev :(

**Comment by dfirfpi** [comment]
Hi @estazz 
did you install pycryptodome? Most likely you're using WSL, try
`pip3 install pycryptodome` or `python3 -m pip install pycryptodome`

**Comment by estazz** [comment]
Hi @dfirfpi 
thanks for the super quick reply! Everything worked as supposed after installing pycrptodome. Didn't read about it in the first time. Thanks alot!
